---
# Install Nexus 

- name: Add the user Nexus to group Nexus
  user:
    name: nexus
    comment: nexus artifactory user

- name: Create /app/ directory for Nexus
  file:
    path: /app/
    state: directory
    mode: 0755

- name: Unarchive a Nexus tar under /app/
  unarchive:
    src: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /app/
    remote_src: yes

- name: Rename Nexus dir
  shell: mv /app/nexus* /app/nexus

- name: Set up user as nexus
  lineinfile:
    path: /app/nexus/bin/nexus.rc
    regexp: '^#run'
    line: run_as_user="nexus"
   
- name: Changing permission of /app/ directory
  file:
    path: /app/
    state: directory
    owner: nexus
    group: nexus
    recurse: yes

- name: Start Nexus
  shell: /app/nexus/bin/nexus start

- name: Waiting for Nexus connection 
  wait_for:
    host: 0.0.0.0
    port: 8081
    state: present
