---
# Install Jenkins 

- name: Install java,unzip and wget
  yum:
    name:
      - wget
      - java-1.8.0-openjdk-devel
      - unzip

- name: Download jenkins.repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Ensure Jenkins is Installed
  yum :
    name: jenkins
    state: present

- name: Replacing port 8080 to 9090 /etc/sysconfig/jenkins from J2 template 
  template:
    src: templates/jenkins.j2
    dest: /etc/sysconfig/jenkins

- name: Start & Enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: Waiting for Jenkins connection 
  wait_for:
    host: 0.0.0.0
    port: 9090
    state: present
