---
# Install Tomcat 

- name: Install tomcat and other packages of tomcat 
  yum:
    name:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps
      - tomcat-docs-webapp
      - tomcat-javadoc

- name: Adding user - jenkins-deployer in /etc/tomcat/tomcat-users.xml 
  copy:
    src: files/tomcat-users.xml
    dest: /etc/tomcat/tomcat-users.xml
    backup: yes

- name: Start & Enable Tomcat
  systemd:
    name: tomcat
    state: started
    enabled: true

- name: Waiting for Tomcat connection 
  wait_for:
    host: 0.0.0.0
    port: 8080
    state: present
